appMainTitle = "UWISpace Importer"

locale = "en"

wizardWidth = "1280"
wizardHeight = "720"

[DSpace]
dspaceRestURL = "http://localhost:8081/server"

# metadata fields not to be removed when item metadata is updated - comma delimited list
metadataNotRemoveUpdate = "dc.identifier.uri, dc.description.provenance, dc.date.available, dc.date.accessioned"

# set provenance.enabled to true to activate this option, false to deactivate
# provenance value for insert and update, use place holders for current user - {u}, current timestamp - {t}
provenance.enabled = "true"
provenance.metadata.field = "dc.description.provenance"
provenance.add = "Added to DSpace by {u} on {t} using batch upload"
provenance.update = "Updated by {u} on {t} using batch upload"
